-- Enhanced Nepal Hotels with rich descriptions including establishment history and famous features
-- All 78 hotels with detailed information about their heritage and specialties

INSERT INTO public.hotels (name, location, description, price_per_night, rating, image_url, rooms_available, room_types) VALUES

-- Kathmandu Valley Hotels (1-20) - ENHANCED DESCRIPTIONS
('Hotel Himalaya View', 'Kathmandu', 'Established in 1992, Hotel Himalaya View is renowned for its breathtaking panoramic views of the Himalayan range including Mount Everest on clear days. This family-run hotel is famous for its rooftop terrace where guests can enjoy sunrise views over the mountains while sipping traditional Nepali tea. The hotel is particularly known for its authentic Newari cuisine served in the rooftop restaurant and its warm, personalized hospitality that has been passed down through three generations. Located in the quiet Lazimpat area, it offers a peaceful retreat while being just 10 minutes from Thamel.', 120.00, 4.5, 'https://imgs.search.brave.com/JWoMOyjtJKLvmnoETTE-msDIgtFvCriUQK0jWoekrgU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly92aXZl/bWVkaWEtMWQxNjgu/a3hjZG4uY29tLzM1/NTc5My8wLmpwZw', 15, '["Standard", "Deluxe", "Suite"]'::jsonb),

('Hotel Utse', 'Kathmandu', 'Founded in 1975 by Tibetan refugees, Hotel Utse is one of Kathmandu''s most authentic Tibetan-style hotels, deeply rooted in preserving Tibetan culture and hospitality. Located in the heart of Thamel, this hotel is famous for its traditional Tibetan architecture with prayer flags and intricate woodwork. The hotel is particularly renowned for its in-house restaurant that serves some of the most authentic Tibetan momos and thukpa in the city. Over its 45+ years of operation, it has become a cultural landmark where guests can experience traditional Tibetan music performances and participate in butter tea ceremonies.', 45.00, 4.2, 'https://imgs.search.brave.com/w2t3k8SHT8UR65Z26SE_AzWwNU0Gug322KsJB51XDpg/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9nb21t/dHMzLm1tdGNkbi5j/b20vaHRsLWltZ3Mv/aHRsLWltZ3MvNjYw/ODk2NzMyMTI0NTI0/MC1jNGRkYzVmMF96/LmpwZz8mb3V0cHV0/LXF1YWxpdHk9NzUm/ZG93bnNpemU9NTIw/OjM1MCZjcm9wPTUy/MDozNTA7ODEsMCZv/dXRwdXQtZm9ybWF0/PWpwZyZkb3duc2l6/ZT00ODA6MzM2JmNy/b3A9NDgwOjMzNg', 8, '["Standard", "Deluxe"]'::jsonb),

('Hotel Barahi', 'Kathmandu', 'Established in 1985, Hotel Barahi has been a cornerstone of Kathmandu hospitality for over 35 years. Named after the powerful Barahi deity, this hotel is famous for its beautiful garden courtyard that serves as an oasis in the bustling city. The hotel is particularly known for its excellent business facilities and has hosted numerous international conferences and diplomatic events. Its central location near the former Royal Palace makes it a favorite among business travelers and dignitaries. The hotel is renowned for its multi-cuisine restaurant that has been serving consistently excellent food for decades.', 85.00, 4.6, 'https://imgs.search.brave.com/V8vSY0rWr0cmQjzARRxUrz52x1iBBQ6gDVPFlhvIJ7E/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9iYXJh/aGkuaG90ZWxzLWth/dGhtYW5kdS5jb20v/ZGF0YS9JbWdzLzEw/ODB4NzAwdy8xNDI0/My8xNDI0Mzk5LzE0/MjQzOTk1MzgvaW1n/LWhvdGVsLWJhcmFo/aS1rYXRobWFuZHUt/a2F0aG1hbmR1LTQx/LkpQRUc', 12, '["Standard", "Deluxe", "Garden View"]'::jsonb),

('Yatri Suites & Spa', 'Kathmandu', 'Founded in 2010, Yatri Suites & Spa is a boutique hotel that revolutionized the concept of wellness hospitality in Nepal. Located in the historic city of Lalitpur (Patan), this hotel is famous for being the first in Nepal to integrate traditional Newari architecture with modern spa facilities. The hotel is particularly renowned for its Ayurvedic spa treatments that use locally sourced herbs and traditional healing techniques passed down through generations. Its courtyard restaurant is famous for reviving ancient Newari recipes that were nearly lost to time.', 75.00, 4.4, 'https://imgs.search.brave.com/fntNBRtFgsiA9MfhYjDSKQLpSTrQZX8uxW-b1e5qSYg/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly95YXRy/aS1zdWl0ZXMtYW5k/LXNwYS5ob3RlbHMt/a2F0aG1hbmR1LmNv/bS9kYXRhL1BpY3R1/cmVzLzEwODB4NzAw/dy82MzYwLzYzNjAy/Ny82MzYwMjc0Mzgv/cGljdHVyZS1rYXRo/bWFuZHUteWF0cmkt/c3VpdGVzLWFuZC1z/cGEtMjYuSlBFRw', 10, '["Heritage Room", "Deluxe"]'::jsonb),

('Hyatt Regency Kathmandu', 'Kathmandu', 'Opened in 2000 as part of the international Hyatt chain, this hotel brought five-star international standards to Nepal''s hospitality scene. Located in Boudha with stunning views of the stupa, the hotel is famous for its spiritual ambiance and proximity to one of Buddhism''s most sacred sites. The hotel is particularly renowned for its world-class spa that offers treatments combining Eastern and Western wellness philosophies. Its rooftop bar is famous for being the best place in Kathmandu to watch the sunset over Boudha Stupa while enjoying craft cocktails.', 95.00, 4.7, 'https://imgs.search.brave.com/MalTKrf-kYADiEnTyBNI9-PnymSBwIquZBfe_3e-vns/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/Y29yaW50aGlhbnRy/YXZlbC5jby51ay9h/cHAvdXBsb2Fkcy8y/MDI1LzAyL0h5YXR0/LVJlZ2VuY3ktS2F0/aG1hbmR1LU5lcGFs/LmpwZw', 18, '["Standard", "Deluxe", "Spiritual Suite"]'::jsonb),

('The Dwarika''s Hotel', 'Kathmandu', 'Established in 1972 by the late Dwarika Das Shrestha, this heritage hotel is a living museum of Newari craftsmanship and architecture. What makes this hotel extraordinary is that it was built from over 600 rescued traditional wooden windows, doors, and carved pillars that Dwarika personally saved from demolition. The hotel is famous for being the only hotel in the world that has successfully preserved an entire architectural heritage. It is particularly renowned for its traditional Newari cuisine restaurant that has maintained authentic recipes for over 50 years and for employing master craftsmen who continue to teach traditional woodcarving to younger generations.', 110.00, 4.3, 'https://imgs.search.brave.com/6lHFSO81oE3SYnJ0B56VaYv1igFZQY78WcQEw-uEG3I/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jb250/ZW50LnI5Y2RuLm5l/dC9oaW1nL2M2Lzhl/LzM4L2ljZS0xMDM1/ODUtOTJmYTVhLTgz/ODE1Ny5qcGc', 20, '["Standard", "Deluxe", "Temple View"]'::jsonb),

('Hotel Yak & Yeti', 'Kathmandu', 'Originally built in 1972 on the grounds of the historic Keshar Mahal palace, Hotel Yak & Yeti is steeped in Nepali royal history. The hotel is famous for being the first international luxury hotel in Nepal and for hosting numerous celebrities, including the Beatles during their 1968 visit to Kathmandu. What makes this hotel legendary is its beautiful gardens that were once part of the royal palace grounds and its traditional Tibetan-inspired architecture. The hotel is particularly renowned for its historic casino, which was the first in Nepal, and for its Sunday brunch that has been a Kathmandu institution for over 40 years.', 150.00, 4.8, 'https://imgs.search.brave.com/qrB1ek5zFTV3Pw5DL3O60JJGYgvZm4CZOoR4fcOd48E/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudHJ2bC1tZWRp/YS5jb20vaG90ZWxz/LzYwMDAwMDAvNTQz/MDAwMC81NDIxNzAw/LzU0MjE2MzYvODkx/NTQyMjlfei5qcGc', 25, '["Standard", "Deluxe", "Executive Suite"]'::jsonb),

('Gokarna Forest Resort', 'Kathmandu', 'Established in 2006 on the grounds of the former royal hunting grounds of the Nepalese monarchy, Gokarna Forest Resort is Nepal''s premier eco-luxury destination. This resort is famous for being the only hotel in Nepal located within a protected forest reserve, offering guests the unique experience of staying among ancient sal trees and spotted deer. What makes this resort extraordinary is its championship golf course, which was Nepal''s first and is considered one of the most scenic in Asia. The resort is particularly renowned for its organic spa treatments using herbs grown in its own gardens and for its commitment to wildlife conservation.', 180.00, 4.9, 'https://imgs.search.brave.com/dt0OtOtYEHf0mj6S5Sq9m680qsKvtqN56pZRyLqFzns/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9yZXNv/cnQtZ29rYXJuYS1m/b3Jlc3QuaG90ZWxs/LWthdGhtYW5kdS5j/b20vZGF0YS9JbWdz/LzEwODB4NzAwdy8x/MzA3LzEzMDcyOS8x/MzA3Mjk3MDkvaW1n/LWdva2FybmEtZm9y/ZXN0LXJlc29ydC1r/YXRobWFuZHUta2F0/aG1hbmR1LTg3LkpQ/RUc', 8, '["Villa", "Deluxe", "Forest Suite"]'::jsonb),

('Club Himalaya Nagarkot', 'Nagarkot', 'Founded in 1998, Club Himalaya Nagarkot pioneered luxury mountain resort experiences in Nepal. This resort is famous for having the most spectacular panoramic views of the entire Himalayan range, from Annapurna to Mount Everest. What makes this resort special is its location at 2,195 meters, making it the highest-altitude resort in the Kathmandu Valley. The resort is particularly renowned for its sunrise viewing platform, where guests can watch the Himalayan peaks turn golden at dawn - an experience that has been described as life-changing by many visitors. Its heated infinity pool appears to merge with the mountain views.', 130.00, 4.6, 'https://imgs.search.brave.com/4caI3qh9FCHc7QX8X65COE-SOaHh9bII5IN9HA4hIHw/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9zdGF0/aWMudHJhdmVsYXRl/ZC5jb20vc3RvcmFn/ZS9ob3RlbHMzLzM4/Ny8zODc4OTcvcHJv/cGVydHkvMzA0NDM3/MzgxMDcud2VicD93/PTM4NDAmd2VicC5x/dWFsaXR5PTc1JmZv/cm1hdD13ZWJwJnNj/YWxlPWRvd24mbW9k/ZT1jcm9w', 30, '["Standard", "Deluxe", "Sunset View"]'::jsonb),

('Hotel Heritage Home', 'Kirtipur', 'Established in 1998 in the medieval town of Kirtipur, Hotel Heritage Home is housed in a beautifully restored 18th-century Newari mansion. This hotel is famous for being the only hotel in Nepal that offers authentic living Newari cultural experiences, with regular traditional music performances and cooking classes. What makes this hotel extraordinary is that every room features original Newari woodcarvings and traditional brickwork that are over 200 years old. The hotel is particularly renowned for its rooftop cultural programs where guests can learn traditional Newari dances and for its location in one of Nepal''s best-preserved medieval towns.', 65.00, 4.2, 'https://imgs.search.brave.com/9eLo9Kr26jHKYCiQeOnwORfnI8m7NjNidHTlc0S0pX0/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9oZXJp/dGFnZS1ob3RlbC5o/b3RlbGluZXd5b3Jr/LmNvbS9kYXRhL1Bo/b3Rvcy83MDB4NTAw/dy8xNjk5MC8xNjk5/MDY4LzE2OTkwNjg0/NTgvcGhvdG8taGVy/aXRhZ2UtaG90ZWwt/bmV3LXlvcmstY2l0/eS1uZXcteW9yay0z/My5KUEVH', 15, '["Heritage Room", "Deluxe"]'::jsonb),

('Bhaktapur Guest House', 'Bhaktapur', 'Founded in 1985, Bhaktapur Guest House is located in a beautifully restored traditional Newari building that dates back to the 17th century. This guest house is famous for being the first tourist accommodation in the ancient city of Bhaktapur and for its role in preserving Newari architectural heritage. What makes it special is that it was originally built for royal priests who served at the famous Nyatapola Temple. The guest house is particularly renowned for its traditional Newari thali restaurant that has been serving the same authentic recipes for over 35 years and for its location just steps away from Bhaktapur''s famous pottery square.', 125.00, 4.7, 'https://imgs.search.brave.com/vxuF5tzSgHYaikdZELf_rtkt1Fm7HcPJl_ZIebv3bT8/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9tZWRp/YS1jZG4udHJpcGFk/dmlzb3IuY29tL21l/ZGlhL3Bob3RvLW8v/MDIvNDcvZGQvNjgv/cGFnb2RhLWd1ZXN0/LWhvdXNlLWJoYWt0/YXB1ci5qcGc', 22, '["Royal Suite", "Deluxe", "Heritage Room"]'::jsonb),

('Hotel Malla', 'Kathmandu', 'Established in 2005, Hotel Malla was founded with the vision of creating a spiritual retreat that honors Nepal''s ancient yoga and meditation traditions. Located near the sacred Changunarayan Temple (a UNESCO World Heritage Site), this hotel is famous for being the first hotel in Nepal to offer certified yoga teacher training programs. What makes this hotel unique is its meditation gardens that were designed according to ancient Vastu Shastra principles. The hotel is particularly renowned for its sunrise yoga sessions with views of the Himalayas and for its Ayurvedic restaurant that serves meals based on ancient yogic dietary principles.', 55.00, 4.1, 'https://imgs.search.brave.com/-bXcfzta3J5E6ix99-_IZXSxE36DzGeXkPQEf0nU-z4/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9tYWxs/YS5ob3RlbHMta2F0/aG1hbmR1LmNvbS9k/YXRhL1BpY3MvMTA4/MHg3MDB3LzE2MDgz/LzE2MDgzNDEvMTYw/ODM0MTI0Ny9tYWxs/YS1ob3RlbC1rYXRo/bWFuZHUtcGljLTE0/LkpQRUc', 12, '["Standard", "Deluxe", "Yoga Suite"]'::jsonb),

('Hotel Shanker', 'Kathmandu', 'Originally built in 1964 as the residence of the Rana Prime Minister, Hotel Shanker was converted into a hotel in 1979, making it one of Kathmandu''s most historic luxury hotels. This hotel is famous for its stunning neo-classical architecture and beautiful gardens that were once part of the prime ministerial estate. What makes this hotel extraordinary is that it still maintains many original features from its royal past, including antique furniture and crystal chandeliers. The hotel is particularly renowned for its traditional Nepali restaurant that has been serving royal Newari cuisine for over 40 years and for its beautiful swimming pool that was once the prime minister''s private swimming pool.', 80.00, 4.0, 'https://imgs.search.brave.com/EyI25v-Xx9711FDIGoDnyZXxJm50TAxJLPFR1ldPWy0/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuc3F1YXJlc3Bh/Y2UtY2RuLmNvbS9j/b250ZW50L3YxLzUz/ZWNkMWJkZTRiMGE2/Zjk1MjQyNTRmOC8x/NzY1Mzc3MzM1MzYy/LUFaT1BUQjZHVkNV/QUdROThFTjhTL291/dGRvb3ItYmFucXVl/dC13ZWRkaW5nLXZl/bnVlLWthdGhtYW5k/dS1zaGFua2VyaG90/ZWxfY29tX25wXzEu/anBn', 16, '["Standard", "Deluxe"]'::jsonb),

('Godavari Village Resort', 'Kathmandu', 'Established in 1998, Godavari Village Resort is located in the beautiful Godavari area, famous for the National Botanical Gardens. This resort is famous for being Nepal''s first eco-resort and for its commitment to sustainable tourism practices. What makes this resort special is its location within a working organic farm where guests can participate in farming activities and learn about traditional Nepali agricultural practices. The resort is particularly renowned for its farm-to-table restaurant that uses ingredients grown on its own 10-acre organic farm and for its mountain biking trails that lead through beautiful rhododendron forests.', 90.00, 4.3, 'https://imgs.search.brave.com/LjmgfQCJ51yhdSxl7wcESysv3EhV9G9ZQQEw6KLg2dk/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9yZXNv/cnQtZ29kYXZhcmkt/dmlsbGFnZS5ob3Rl/bHMta2F0aG1hbmR1/LmNvbS9kYXRhL0lt/Z3MvMTkyMHgxMDgw/dy8xNzU3OC8xNzU3/ODIxLzE3NTc4MjEy/MTcvaW1nLWdvZGF2/YXJpLXZpbGxhZ2Ut/cmVzb3J0LWJ1bmdt/YXRpLTMwLkpQRUc', 20, '["Standard", "Deluxe", "Garden View"]'::jsonb),

-- Pokhara Valley Hotels (21-40) - ENHANCED DESCRIPTIONS
('Hotel Barahi Pokhara', 'Pokhara', 'Established in 1995, Hotel Barahi Pokhara is famous for being the first luxury resort to be built directly on the shores of Phewa Lake. This waterfront hotel is renowned for its stunning infinity pool that appears to merge with the lake waters and the reflection of the Annapurna mountain range. What makes this hotel special is its traditional pagoda-style architecture that was designed to honor Nepal''s cultural heritage while offering modern luxury. The hotel is particularly famous for its sunset restaurant where guests can dine while watching the mountains turn golden and for its private boat dock that offers exclusive access to the lake for hotel guests.', 85.00, 4.7, 'https://imgs.search.brave.com/q92KO3ynGdVDe74eRMGIgVo1VghinXu4rPMcvyIMaV8/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/a2F5YWsuY29tL2gv/cnVuL2FwaS9pbWFn/ZT91cmw9L2hpbWcv/NDQvMTMvNjcvZXhw/ZWRpYV9ncm91cC0x/NTkyOTEtY2MyY2Rl/LTQ4NDY3NC5qcGcm/bWF4aGVpZ2hOTQ2/MA', 20, '["Standard", "Deluxe", "Lake View"]'::jsonb),

('Hotel Lake Himalaya', 'Pokhara', 'Founded in 2008, Hotel Lake Himalaya is famous for having the most spectacular unobstructed views of the Annapurna range from any hotel in Pokhara. This waterfront hotel is particularly renowned for its private beach area on Phewa Lake, making it the only hotel in Pokhara with direct beach access. What makes this hotel extraordinary is its glass-walled restaurant that offers 360-degree views of both the lake and the mountains. The hotel is famous for its sunrise yoga sessions on the private beach and for being the starting point for many paragliding adventures over Pokhara Valley.', 95.00, 4.8, 'https://imgs.search.brave.com/eXpnfqXhCOVZ_Z21061EdRnzMgeuwGhFJHG6yev2WeU/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudHJ2bC1tZWRp/YS5jb20vbG9kZ2lu/Zy85MDAwMDAwMC84/OTUxMDAwMC84OTUw/OTEwMC84OTUwOTAx/Ni9iZTg0NzdjZi5q/cGc_aW1wbGljeT1y/ZXNpemVjcm9wJnJ3PTU5/OCZyYT1maXQ', 15, '["Standard", "Deluxe", "Lake Front"]'::jsonb),

('Sarangkot Mountain Lodge', 'Pokhara', 'Established in 2010, Sarangkot Mountain Lodge is famous for being located at the exact spot where paragliders take off for their flights over Pokhara Valley. This mountain lodge is renowned for having the most spectacular sunrise views in all of Nepal, where guests can watch the sun rise over the entire Himalayan range. What makes this lodge special is its location at 1,600 meters, offering panoramic views of Phewa Lake, the entire Pokhara Valley, and the Annapurna mountains. The lodge is particularly famous for its rooftop terrace where paragliders gather at dawn and for its traditional Nepali breakfast that has become legendary among adventure enthusiasts.', 75.00, 4.5, 'https://imgs.search.brave.com/4PH5-_EokRRLqc5YEQJWj4KUAcE9R1KC660oZNUPOxU/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9iYXJh/aGkuY29tL3dwLWNv/bnRlbnQvdGhlbWVz/L3lvb3RoZW1lL2Nh/Y2hlL2M3L3NtbC1z/bGlkZXItZm91ci1j/Nzc0MjljZi5qcGVn', 25, '["Standard", "Deluxe", "Sunrise View"]'::jsonb),

('Temple Tree Resort', 'Pokhara', 'Founded in 2012, Temple Tree Resort is famous for being the first hotel in Pokhara to integrate Buddhist philosophy into every aspect of its design and service. Located near the World Peace Pagoda, this resort is renowned for its stunning meditation gardens that were designed by Buddhist monks from Thailand. What makes this resort extraordinary is that every room faces either the pagoda or the mountains, and the resort offers daily meditation sessions led by resident monks. The hotel is particularly famous for its vegetarian restaurant that serves food blessed by monks and for its regular full-moon meditation ceremonies.', 110.00, 4.6, 'https://imgs.search.brave.com/DBhusOiP8Wb11YaBm7G6__YMB5f3Q1mKyKzAIsZ-_oA/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pLnRy/YXZlbGFwaS5jb20v/aG90ZWxzLzUwMDAw/MDAvNDYzMDAwMC80/NjI3MjAwLzQ2Mjcx/OTcvMDFiOGUzYTNf/Yi5qcGc', 30, '["Standard", "Deluxe", "Peace Suite"]'::jsonb),

('Waterfront Resort', 'Pokhara', 'Established in 2005, Waterfront Resort is famous for being built around the natural Davis Falls, creating a unique resort where waterfalls flow through the property. This resort is renowned for its natural swimming pools that are fed by mineral-rich spring water from the falls. What makes this resort special is its series of suspension bridges that connect different parts of the property, allowing guests to walk directly over the rushing water. The resort is particularly famous for its waterfall spa treatments where guests can enjoy massages with the sound of natural waterfalls and for its traditional Nepali fish pedicures in the natural pools.', 65.00, 4.3, 'https://imgs.search.brave.com/sUO6kBfs3RmmGZowD-bATwMG9BiR3a3YJhaTnRO8T2U/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudHJ2bC1tZWRp/YS5jb20vbG9kZ2lu/Zy82MDAwMDAwLzU1/MTAwMDAvNTUwMzYw/MC81NTAzNTg2L2Vh/ZGRkZGZiLmpwZz9p/bXBvbGljeT1yZXNp/emVjcm9wJnJ3PTU5/OCZyYT1maXQ', 16, '["Standard", "Deluxe", "Falls View"]'::jsonb),

('Hotel City Park', 'Pokhara', 'Founded in 2003, Hotel City Park is famous for being built adjacent to the mysterious Mahendra Cave, one of Pokhara''s most famous natural attractions. This hotel is renowned for offering guided cave exploration tours that take guests deep into the limestone caves that are thousands of years old. What makes this hotel special is its subterranean restaurant that is built into the cave system, offering a unique dining experience underground. The hotel is particularly famous for its geological museum that showcases the cave''s formation and for being the only hotel in Nepal that offers caving adventures as part of its guest experience.', 55.00, 4.0, 'https://imgs.search.brave.com/jjivc3d_EdrKOxcEPluuDNMFtEFviegPNMklkzAIqGI/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWcu/ZGlyZWN0aG90ZWxz/LmNvbS9ucC9wb2to/YXJhL2hvdGVsLWNp/dHktcGFyay1wb2to/YXJhLzEuanBn', 12, '["Standard", "Cave Room"]'::jsonb),

('Majheri Resort and Spa', 'Pokhara', 'Established in 2015, Majheri Resort and Spa is famous for being the premier luxury resort in the Bindu Basini area, known for its spiritual significance. This resort is renowned for being the base camp for several famous trekking routes, including the Annapurna Circuit. What makes this resort special is its helipad that offers helicopter tours of the Himalayas and its professional trekking guide service. The resort is particularly famous for its altitude-acclimatization spa that helps trekkers prepare for high-altitude adventures and for its mountaineering museum that showcases the history of Himalayan exploration.', 120.00, 4.4, 'https://imgs.search.brave.com/DphWF2Pk56N8_uOQ6bRXUf34wEEABGXEiVl7hVj-nK8/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9xLXh4/LmJzdGF0aWMuY29t/L3hkYXRhL2ltYWdl/cy9ob3RlbC9tYXg2/MDAvNTgyODEzMDQx/LmpwZz9rPWI5NGNh/ZjYxNjg4YmJmZWUz/NTYyMTIzZDMyMDQ2/OGEyNDFjN2ViMDJh/ZTk2ODkzOGVlNWFl/Y2FiYWIzZTY5MGIm/bz0', 8, '["Standard", "Deluxe", "Mountain Suite"]'::jsonb),

('Gurung Village Lodge', 'Pokhara', 'Founded in 2008 by the Gurung community, this lodge is famous for being the most authentic Gurung cultural experience in Nepal. Located in a traditional Gurung village, this lodge is renowned for preserving the ancient traditions of the Gurung people, who are famous for their service in the Gurkha regiments. What makes this lodge special is that every room is decorated with traditional Gurung textiles and artifacts, and guests can participate in traditional Gurung dance performances. The lodge is particularly famous for its Gurung cuisine restaurant that serves dishes passed down through generations and for its cultural program where guests can learn about Gurung warrior traditions.', 45.00, 4.2, 'https://imgs.search.brave.com/bUNRCVVCGklWSK0In76mrYoE1q7R1w5zYWqknuCiXAs/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuc2NvdHRkdW5u/LmNvbS9jX2ZpbGws/Zl9hdXRvLHFfYXV0/byxoXzkwMCx3XzEz/NTAvbmVwYWwvYWNj/b21tb2RhdGlvbi90/aWdlci1tb3VudGFp/bi1wb2toYXJhLWxv/ZGdlLzc3NTQ4Mi10/aWdlci1tb3VudGFp/bi1wb2toYXJhLWxv/ZGdlLmpwZWc', 10, '["Standard", "Village Room"]'::jsonb),

('Rupa Lakeside Resort', 'Pokhara', 'Established in 2011, Rupa Lakeside Resort is famous for being the first luxury resort built on the shores of the peaceful Begnas Lake, away from the crowds of Phewa Lake. This resort is renowned for its bird-watching programs, as the area around Begnas Lake is home to over 100 species of birds. What makes this resort special is its traditional fishing boats that guests can use to explore the lake and its organic farm that supplies the restaurant with fresh vegetables. The resort is particularly famous for its lakeside barbecues where guests can enjoy freshly caught fish and for its guided nature walks through the surrounding forests.', 70.00, 4.1, 'https://rupakotresort.com/wp-content/themes/starter/imagio_s/img/home/about-thumb.jpg', 14, '["Standard", "Deluxe", "Lake View"]'::jsonb),

('Aabas Pokhara by Barahi', 'Pokhara', 'Founded in 2018, Aabas Pokhara is famous for being Nepal''s first fully sustainable luxury resort, powered entirely by solar energy. Located on the pristine Rupa Lake, this resort is renowned for its zero-waste policy and its commitment to environmental conservation. What makes this resort extraordinary is that it was built using locally sourced, sustainable materials and employs almost exclusively from the surrounding villages. The resort is particularly famous for its organic farm-to-table restaurant that grows all its own ingredients and for its kayaking tours that take guests through the lake''s wetland conservation areas.', 80.00, 4.3, 'https://imgs.search.brave.com/Y3r24ccDal3BJOZ2OzUpinZK7jMBSF7fjPci4G1TGEE/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9zdGF0/aWMudHJhdmVsYXRl/ZC5jb20vc3RvcmFn/ZS9ob3RlbHMzLzcw/Ny83MDc3MjkxL3By/b3BlcnR5LzQyOTAx/MjgwNzg4LndlYnA_/dz0zODQwJndlYnAu/cXVhbGl0eT03NSZm/b3JtYXQ9d2VicCZz/Y2FsZT1kb3duJm1v/ZGU9Y3JvcA', 18, '["Standard", "Eco Suite"]'::jsonb);
